### ISSUE TITLE
Having issues running the demo

### ISSUE THREAD

**Issue by ericxtang** [jordicenzano/lhls-simple-live-platform#1] opened 2020-06-26 04:13 UTC
Hi @jordicenzano,
Thank you for publishing this demo!  I tried to reproduce it and ran into some issues.  I've recorded the issue [here](https://www.loom.com/share/9932121bef444e77af2878a238ce6dcd).  Please take a look.  I'd love to get this working in my dev environment.

**Comment by jordicenzano** [comment] 2020-06-26 13:31
Hi, you are totally right I reproduced the problem really easy. Try Safari and/or quicktime. I will take a look when I have a change but my guess is ffmpeg does NOT like HTTP chunked transfer

Thanks to your feedback I updated the guide: "Tested with following players: Safari, and Quicktime (there is a known problem with ffplay)"

**Comment by jordicenzano** [comment] 2020-06-26 13:31
Closing because there is a workaround (using other players: Safari and/or quicktime.)

**Closed as completed by jordicenzano** 2020-06-26 13:31 UTC

**Comment by ericxtang** [comment] 2020-06-26 14:17
Hi @jordicenzano - sorry I forgot to record in the previous video - I couldn't get Safari or Quicktime to work either.  Here is [another video](https://www.loom.com/share/7993259c9d90443e93517890912b8d19) for that

**Comment by jordicenzano** [comment] 2020-06-26 14:46
Could you show in a video (or post a screenshot) the network tab of dev utils in Safari

Instead of `./transcoding-multirendition-rtmp.sh live` could you try `./transcoding-multirendition-rtmp.sh test` (the script will also generate a test video for you, so no need for OBS)

PS: You have the same Safari version as me

**Comment by ericxtang** [comment] 2020-06-26 15:24
When I run the test video, it plays for a few seconds, and then hangs.  Safari seems to get stuck trying to load the segments, but also the video ingest seems to stop.  So it's unclear if the ingest is the problem or the playback is the problem.  

I ran this a few times, and noticed that the ingest runs fine if I don't watch the video. I see that you write files to disk and then pipe them into the ts segment server.  Do you think it could be something going on with the file upload/download path?  

<img width="1567" alt="Screen Shot 2020-06-26 at 11 16 52 AM" src="https://user-images.githubusercontent.com/345743/85873096-ab9b0300-b79e-11ea-9041-037776ae931f.png">
<img width="1125" alt="Screen Shot 2020-06-26 at 11 16 57 AM" src="https://user-images.githubusercontent.com/345743/85873104-ad64c680-b79e-11ea-9568-8aecd04c3214.png">

**Comment by jordicenzano** [comment] 2020-06-26 21:24
Thanks a lot for being persistent. I did find a deadlock in the [go-chunked-streaming-server](https://github.com/mjneil/go-chunked-streaming-server), and I just committed a [fix](https://github.com/mjneil/go-chunked-streaming-server/commit/868fcc44a61ae92e4c64c665cb1755c4ab3c510a). Now it should work for any player (it works for `ffplay` too)

You just need to:
- `git pull` the last `master` version of [go-chunked-streaming-server](https://github.com/mjneil/go-chunked-streaming-server)
- And `make`

**Comment by ericxtang** [comment] 2020-06-27 04:39
Ahh - those file deletions.  

Thanks for fixing the issue!  Now it works really well.  This is gonna help me get some early CDN testing done before we add LLHLS into Livepeer :)
